name: Python Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run main.py and capture output
      id: run_hello
      run: |
        output=$(python main.py)
        echo "output=$output" >> $GITHUB_ENV
        echo "$output"

    - name: Verify output
      run: |
        if [[ "${{ env.output }}" == *"Hello, World!"* ]]; then
          echo "Output is as expected."
        else
          echo "Output is not as expected."
          exit 1
        fi
